### ISSUE TITLE
Refine Interruption Handling

### ISSUE THREAD

**Issue by thy-hoang-nn** [Finity-Alpha/OpenVoiceChat#43]
Hi,
Thank you for your contribution to the voice-based conversational engine. I'm encountering an issue while reimplementing your code. Specifically, the bot is designed to operate in a streaming mode, but the problem arises when it starts speaking the first processed sentence, the recording then gets interrupted and it doesn’t continue with the rest of the response.. How can fix the issue ?

**Comment by fakhirali** [comment]
Hmm, interruptions happen when the bot is speaking and the user says something in between. This stops the bot speaking (audio being played) and lets the user speak.
If you're running main.py try adding the following and see if the error persists. The following line will disable interruptions.
```python
    api_key = os.getenv('DEEPGRAM_API_KEY')
    # ear = Ear_deepgram(silence_seconds=2, api_key=api_key)
    ear = Ear_hf(silence_seconds=2, device=device)
   
    # ----The following line will disable interruption handling----
    ear.interrupt_listen = lambda x: ""

    load_dotenv()

    chatbot = Chatbot_gpt(sys_prompt=llama_sales)
```
p.s
Also since the lib is in alpha rn, would recommend installing using ```pip install git+https://github.com/Finity-Alpha/OpenVoiceChat.git ```

**Comment by thy-hoang-nn** [comment]
Thanks for your help
